// Generated by CoffeeScript 1.8.0
(function() {
  var addOne, double;

  addOne = function(a) {
    return a + 1;
  };

  double = function(b) {
    return 2 * b;
  };

  describe('compose', function() {
    return describe('given 2 functions', function() {
      return it('returns a function that, when applied, performs the application of both', function() {
        return expect(compose(double, addOne)(20)).toBe(42);
      });
    });
  });

}).call(this);
